name: Build and package the Mac version

on:
  push:
    branches:
      - master

jobs:
  build-app:
    name: Build for Mac
    runs-on: macos-latest
    env:
      PYTHONVERSION: "3.11.0"
      MACOSX_DEPLOYMENT_TARGET: "12"

    steps:
      - uses: actions/checkout@v2

      - name: Cache Python download
        id: cache-python-download
        uses: actions/cache@v3
        with:
          path: ~/python.pkg
          key: macOS-Python-${{ env.PYTHON_VERSION }}

      - name: Get Python
        run: |
          curl https://www.python.org/ftp/python/${PYTHONVERSION}/python-${PYTHONVERSION}-macos11.pkg -o ~/python.pkg

      - name: Install Python
        run: sudo installer -pkg ~/python.pkg -target /

      - name: Install Python dependencies and build
        run: |
          python3 --version
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade pip wheel
          python3 -m pip install -r requirements.txt
          python3 -m pip install pyinstaller
          python3 -O -m PyInstaller DIP.spec

      - name: Log files
        run: |
          ls dist
          ls dist/DIP
          mkdir DIP

      - name: Package app
        run: |
          mv ./dist/DIP.app ./DIP/DIP.app
          brew install create-dmg
          test -f DIP.dmg && rm DIP.dmg
          create-dmg \
            --volname "DIP" \
            --volicon "DIP/static/DIP.icns" \
            --icon "DIP.app" 100 100 \
            --app-drop-link 400 100 \
            --window-size 500 300 \
            "DIP.dmg" \
            "DIP/"

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: DIP.dmg
          asset_name: DIP.dmg
          tag: latest-mac-build
          overwrite: true
